### ISSUE TITLE
PR to kornia?

### ISSUE THREAD

**Issue by ducha-aiki** [hmorimitsu/sift-flow-gpu#1]
Hi,

Would you be interested to contribute with a possible adaptation implementation to kornia? 
https://github.com/kornia/kornia

-- 
Best, Dmytro

**Comment by hmorimitsu** [comment]
Hi @ducha-aiki,

I think it would be nice to contribute to kornia. However, I am just not sure if I can do that. This code here is heavily based on the original one. The problem is that it appears that the original code does not have an explicit license, so I do not know how this my code would be considered.

Do you know or have any experience with this type of derivative code and licenses?

Best,

Henrique

**Comment by ducha-aiki** [comment]
If you don't copy, but re-implement, it is fine. Moreover, for the lost of functionality, you need not to use your, or theirs code, because the functions already exist in kornia.
For example, spatial gradient https://kornia.readthedocs.io/en/latest/filters.html#kornia.filters.spatial_gradient or Dense SIFT (in this unmerged PR https://github.com/kornia/kornia/pull/962)

**Comment by hmorimitsu** [comment]
I see, thank you. I'll take a look at kornia and see what I can do.
